name: "Irrigation BSS"
version: "1.4.3"
slug: "irrigation_bss"
description: "Advanced irrigation management — zones, valves, sensors, scheduler"
url: "https://github.com/BSS-Baumgart/bss_ha_irrigation"
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: "mdi:sprinkler"
panel_title: "Irrigation"
panel_admin: false

init: false

homeassistant_api: true
hassio_api: false
auth_api: false

options:
  log_level: "info"
  language: "en"

schema:
  log_level: list(debug|info|warning|error)
  language: list(pl|en|de)

